[package]
name = "qpsk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realfft = "2.0.1"
alsa = "*"
lazy_static = "1.4.0"